server:
  port: 8761

eureka:
  instance:
    hostname: eurekabook-container
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


